### ISSUE TITLE
TypeError: object of type 'long' has no len()

### ISSUE THREAD

**Issue by p5ydn0** [mtfly/sms-bomb#1]
我用windows python2.7运行，为什么会提示“TypeError: object of type 'long' has no len()”错误？

re包问题。

Traceback (most recent call last):
  File "smsbomb.py", line 72, in <module>
    eachLine = sub('phone_number', pn, eachLine)
  File "C:\soft\softinstall\Anaconda2\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\soft\softinstall\Anaconda2\lib\re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "C:\soft\softinstall\Anaconda2\lib\re.py", line 271, in _compile_repl
    p = sre_parse.parse_template(repl, pattern)
  File "C:\soft\softinstall\Anaconda2\lib\sre_parse.py", line 737, in parse_template
    s = Tokenizer(source)
  File "C:\soft\softinstall\Anaconda2\lib\sre_parse.py", line 192, in __init__
    self.__next()
  File "C:\soft\softinstall\Anaconda2\lib\sre_parse.py", line 194, in __next
    if self.index >= len(self.string):
TypeError: object of type 'long' has no len()

**Comment by leochan2017** [comment]
大兄弟，怎么解决的呀。我也遇到了
